export interface Country { name: string; code: string; }

export const COUNTRIES: Country[] = [
    { name: 'Afghanistan',            code: 'AF' },
    { name: 'Albania',                code: 'AL' },
    { name: 'Algeria',                code: 'DZ' },
    { name: 'Angola',                 code: 'AO' },
    { name: 'Argentina',              code: 'AR' },
    { name: 'Australia',              code: 'AU' },
    { name: 'Austria',                code: 'AT' },
    { name: 'Azerbaijan',             code: 'AZ' },
    { name: 'Bahrain',                code: 'BH' },
    { name: 'Bangladesh',             code: 'BD' },
    { name: 'Belgium',                code: 'BE' },
    { name: 'Bolivia',                code: 'BO' },
    { name: 'Bosnia and Herzegovina', code: 'BA' },
    { name: 'Brazil',                 code: 'BR' },
    { name: 'Bulgaria',               code: 'BG' },
    { name: 'Cambodia',               code: 'KH' },
    { name: 'Cameroon',               code: 'CM' },
    { name: 'Canada',                 code: 'CA' },
    { name: 'Chile',                  code: 'CL' },
    { name: 'China',                  code: 'CN' },
    { name: 'Colombia',               code: 'CO' },
    { name: 'Cuba',                   code: 'CU' },
    { name: 'Czech Republic',         code: 'CZ' },
    { name: 'Denmark',                code: 'DK' },
    { name: 'Dominican Republic',     code: 'DO' },
    { name: 'Ecuador',                code: 'EC' },
    { name: 'Egypt',                  code: 'EG' },
    { name: 'El Salvador',            code: 'SV' },
    { name: 'Ethiopia',               code: 'ET' },
    { name: 'Finland',                code: 'FI' },
    { name: 'France',                 code: 'FR' },
    { name: 'Germany',                code: 'DE' },
    { name: 'Ghana',                  code: 'GH' },
    { name: 'Greece',                 code: 'GR' },
    { name: 'Guatemala',              code: 'GT' },
    { name: 'Hungary',                code: 'HU' },
    { name: 'India',                  code: 'IN' },
    { name: 'Indonesia',              code: 'ID' },
    { name: 'Iran',                   code: 'IR' },
    { name: 'Iraq',                   code: 'IQ' },
    { name: 'Ireland',                code: 'IE' },
    { name: 'Israel',                 code: 'IL' },
    { name: 'Italy',                  code: 'IT' },
    { name: 'Jamaica',                code: 'JM' },
    { name: 'Japan',                  code: 'JP' },
    { name: 'Jordan',                 code: 'JO' },
    { name: 'Kazakhstan',             code: 'KZ' },
    { name: 'Kenya',                  code: 'KE' },
    { name: 'Kuwait',                 code: 'KW' },
    { name: 'Lebanon',                code: 'LB' },
    { name: 'Libya',                  code: 'LY' },
    { name: 'Malaysia',               code: 'MY' },
    { name: 'Mexico',                 code: 'MX' },
    { name: 'Morocco',                code: 'MA' },
    { name: 'Mozambique',             code: 'MZ' },
    { name: 'Myanmar',                code: 'MM' },
    { name: 'Nepal',                  code: 'NP' },
    { name: 'Netherlands',            code: 'NL' },
    { name: 'New Zealand',            code: 'NZ' },
    { name: 'Nigeria',                code: 'NG' },
    { name: 'North Korea',            code: 'KP' },
    { name: 'Norway',                 code: 'NO' },
    { name: 'Oman',                   code: 'OM' },
    { name: 'Pakistan',               code: 'PK' },
    { name: 'Palestine',              code: 'PS' },
    { name: 'Peru',                   code: 'PE' },
    { name: 'Philippines',            code: 'PH' },
    { name: 'Poland',                 code: 'PL' },
    { name: 'Portugal',               code: 'PT' },
    { name: 'Qatar',                  code: 'QA' },
    { name: 'Romania',                code: 'RO' },
    { name: 'Russia',                 code: 'RU' },
    { name: 'Saudi Arabia',           code: 'SA' },
    { name: 'Senegal',                code: 'SN' },
    { name: 'Singapore',              code: 'SG' },
    { name: 'Somalia',                code: 'SO' },
    { name: 'South Africa',           code: 'ZA' },
    { name: 'South Korea',            code: 'KR' },
    { name: 'Spain',                  code: 'ES' },
    { name: 'Sri Lanka',              code: 'LK' },
    { name: 'Sudan',                  code: 'SD' },
    { name: 'Sweden',                 code: 'SE' },
    { name: 'Switzerland',            code: 'CH' },
    { name: 'Syria',                  code: 'SY' },
    { name: 'Tanzania',               code: 'TZ' },
    { name: 'Thailand',               code: 'TH' },
    { name: 'Tunisia',                code: 'TN' },
    { name: 'Turkey',                 code: 'TR' },
    { name: 'Uganda',                 code: 'UG' },
    { name: 'Ukraine',                code: 'UA' },
    { name: 'United Arab Emirates',   code: 'AE' },
    { name: 'United Kingdom',         code: 'GB' },
    { name: 'United States',          code: 'US' },
    { name: 'Uruguay',                code: 'UY' },
    { name: 'Venezuela',              code: 'VE' },
    { name: 'Vietnam',                code: 'VN' },
    { name: 'Yemen',                  code: 'YE' },
    { name: 'Zambia',                 code: 'ZM' },
    { name: 'Zimbabwe',               code: 'ZW' },
];

export const COUNTRY_MAP: Record<string, Country> = Object.fromEntries(COUNTRIES.map(c => [c.name, c]));

export function getCountryCode(name: string): string | null {
    return COUNTRY_MAP[name]?.code ?? null;
}

export function getFlagUrl(name: string): string {
    const code = COUNTRY_MAP[name]?.code;
    if (!code) return '';
    // Vector flag — crisp at any display size (avatars, badges, hero banners) unlike the small raster PNGs.
    return `https://flagcdn.com/${code.toLowerCase()}.svg`;
}

// kept for backward compat — returns empty string on Windows since emoji don't work
export function getCountryFlag(_name: string): string { return ''; }
